= GitOps::Quarkus Spring Boot Demo

Demonstrate Quarkus Spring Boot demo.This README details how to deploy the demo *Cloud Native* on to a https://try.openshift.com[OpenShift] cluster.

== Pre-requisites

- https://adoptopenjdk.net/[Java 11]
- https://try.openshift.com[OpenShift4 Cluster]
- OpenShift Serverless (https://knative.dev[Knative])
- OpenShift Pipelines (https://tekton.dev[Tektoncd])
- https://argoproj.github.io/[ArgoCD]
- https://github.com/tektoncd/cli[Tekton CLI]

== Prepare Cluster

Create a OpenShift Admin user and Password, to be able to use the user with OpenShift and Argo CD, it needs to be configured as https://docs.openshift.com/container-platform/4.5/authentication/identity_providers/configuring-htpasswd-identity-provider.html[OpenShift Htpasswd Identity Provider].
To configure the Htpasswd Identity provider, it's required generate a htpasswd file, run the following command to generate the password file:

[source,bash]
----
./mvnw clean package
java -jar target/quarkus-springboot-demo-gitops-runner.jar
----

The command will generate a file called `users.htpass` in link:./openshift/rbac/users.htpass[users.htpass]

[NOTE]
====
* `target/quarkus-springboot-demo-gitops-runner.jar --h` will show available options
* If you don't specify the customization options, the defaults are user  `ocpadmin` with password `adminPa55word!`,
* The identity provider will be configured as part of the link:./gitops/fruits-app-rbac.yaml[Fruits App RBAC]
====

=== Deploy OpenShift Serverless

[source,bash]
----
oc apply -k openshift/cluster/serverless
----

Wait for OpenShift Serverless components to be up and running, check the status using the command:

[source,bash]
----
oc rollout status -n knative-serving deploy activator
oc rollout status -n knative-serving deploy autoscaler
oc rollout status -n knative-serving deploy autoscaler-hpa
oc rollout status -n knative-serving deploy controller
oc rollout status -n knative-serving deploy webhook
----

=== Deploy OpenShift Pipelines

[source,bash]
----
oc apply -k openshift/cluster/pipelines
----

Wait for OpenShift Pipelines components to be up and running, check the status using the command:

[source,bash]
----
oc rollout status -n openshift-pipelines deploy tekton-pipelines-controller
oc rollout status -n openshift-pipelines deploy tekton-pipelines-webhook
oc rollout status -n openshift-pipelines deploy tekton-triggers-controller
oc rollout status -n openshift-pipelines deploy tekton-triggers-webhook
----

=== Deploy Argo CD

[source,bash]
----
oc apply -k openshift/cluster/argocd
----

Wait for Argo CD components to be up and running, check the status using the command:

[source,bash]
----
oc rollout status -n argocd deploy argocd-operator
oc rollout status -n argocd deploy argocd-openshift-oauth-application-controller
oc rollout status -n argocd deploy argocd-openshift-oauth-dex-server
oc rollout status -n argocd deploy argocd-openshift-oauth-redis
oc rollout status -n argocd deploy argocd-openshift-oauth-repo-server
oc rollout status -n argocd deploy argocd-openshift-oauth-server
----

== Deploy Demo

The Application is deployed using Argo CD:

[source,bash]
----
oc apply -k gitops
----

=== GitHub Secret

Navigate to the demo project

[source,bash]
----
oc project quarkus-springboot-demo
----

[IMPORTANT]
====
As the Pipelines will create a PR to GitHub its required that it be provided with a https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[GitHub PAT]:

[source,bash]
----
export GITHUB_PAT_TOKEN=<your-github-pat>
oc create secret \
  -n quarkus-springboot-demo generic image-updater-secret \
  --from-literal=token=$GITHUB_PAT_TOKEN
----
====

=== Setup Webhook

[source,bash]
----
oc get routes -n quarkus-springboot-demo fruits-app-github-webhook
----

Add the url got from the previous command as the https://docs.github.com/en/developers/webhooks-and-events/webhooks[Webhook].

The Knative Service will be deployed but will not have it running since there is no image in the registry. Try a sample push to https://github.com/kameshsampath/quarkus-springboot-demo[Application Repository] to trigger build and deploy of the application.
