apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fruits-app
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/quarkus-springboot-demo/fruits-app@sha256:fe654a4e5a403d835895e83c8a7c967a7a3f487911a8662683e9c51a0a00236c
        imagePullPolicy: Always
        name: user-container
      serviceAccountName: fruits-app-sa
