apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fruits-app
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/quarkus-springboot-demo/fruits-app@sha256:c477fec91d1ed51a69f8b7256a6cbb3253708ca6518d23b22a9dbe1527c91c4f
        imagePullPolicy: Always
        name: user-container
      serviceAccountName: fruits-app-sa
