apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fruits-app
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/quarkus-springboot-demo/fruits-app@sha256:8855e5740dadff7803a13b0e38dfa7cd9eae3883956c642eb29448c07765eec0
        imagePullPolicy: Always
        name: user-container
      serviceAccountName: fruits-app-sa
