apiVersion: v1
kind: Secret
metadata:
  name: gitea-qsbd-demo-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${GIT_REPO}
  password: ${GIT_USER_PASSWORD}
  username: ${GIT_USER}