apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  namespace: openshift-config
spec:
  identityProviders:
    - name: quarkus-springboot-demos-gitops
      type: HTPasswd
      mappingMethod: claim
      htpasswd:
        fileData:
          name: quarkus-springboot-demos