apiVersion: v1
kind: Secret
metadata:
  name: pgsql-credentials
data:
   ## todo move to values
   username: {{ "demo" | b64enc }}
   password: {{ "password!" | b64enc }}
   database: {{ "demodb" | b64enc }} 
   hostname: {{ "postgresql.db.svc.local" | b64enc }} 
   port: {{ "5432" | b64enc }} 